### ISSUE TITLE
Uncommitted patches

### ISSUE THREAD

**Issue by tin2tin** [ResonaBlender/resona#5]
Surprising to see that you have taken this step into forking Blender for improving the VSE. Have you previously tried to submit patches which didn't get committed? I know I have, which is the reason for me leaving Blender development and giving up on my patches. I write to you about them, if there are any of those, you'll find useful in your fork:
https://developer.blender.org/D7679 (Was first committed, and then ditched:)
https://developer.blender.org/D6077
https://developer.blender.org/D6110
https://developer.blender.org/D7914
https://developer.blender.org/D7887
https://developer.blender.org/D7842
https://developer.blender.org/D7707
https://developer.blender.org/D7767
https://developer.blender.org/D7768
https://developer.blender.org/D7916
https://developer.blender.org/D7919
https://developer.blender.org/D7933

There is also this project which cleans up the menus and adds new functions in python:
https://github.com/tin2tin/blender_vse_reworked

**Comment by aldrinmathew1** [comment]
It was great of you to comment on this. Your modifications to the way VSE
behaves is really useful. Can you help in the development of
Resona? Honestly, we need someone to optimise and rework the VSE. We now
have one developer for adding DAW functionality. Another developer is
working on Addons. I am the project lead and I am working on Audio
Nodes, Graphic Design, Project Structure and Planning.
I viewed all the links you provided. I would like to see the changes you
mentioned in this email be implemented in Resona, especially the "Extract
Function", "Youtube 1080p H264 Profile", "Scale to Fit" and "Add Context
Menu".
The changes you proposed like the "Waveform Display as Default" and "Speed
Effect" are already in my Goal Plans. Great to see that the code can be
implemented easily. We have a team on Github. It might not be as organised
as the official Blender Developer's Channel. But there is potential in such
a project. Can you help? Are you free for such an involvement, or are you
busy in any other way? I have sent an invitation on Github to our
organisation and the VSE Team. Let me know...

Regards,
*Aldrin Mathew*

**Comment by aldrinmathew1** [comment]
As this isn't technically an issue, I am closing this. Since your commits to the official VSE are very inspired and ambitious, I have already invited you to our development team. Thanks for this "Issue".

**Comment by tin2tin** [comment]
Thank you for the invite. I'm afraid I'll have to pass on it, as I have have moved to other projects outside of the Blender sphere. 

Before starting this huge project of yours, I think you should spend a little time on investing if your audio ambitions for the VSE, aren't welcome in Blender, by reaching out to Richard on the VSE chat: blender.chat (VSE channel). And also by reaching out to the coder of Audaspace, which is the audio lib used by Blender. It's a project on GitHub. This coder has very limited time himself, but would like to see the audio part of Blender develop. Check out his Gsoc 2020 audio proposal. Maybe he can guide you in a way to get the audio enhancements of yours implemented in Blender(Audaspace has a lot of functions which currently aren't exposed in the Blender UI, including filters. Btw. surround sound is actually implemented, but has very poor UI in the VSE).

If you, for some reason, prefer to do your work outside of Blender, you could consider joining the bforartists project, which has all of the cross platform building etc. set up, but afaik no one to handle VSE/audio stuff. 

Finally, a few more links.
VSE add-ons and news: https://blenderartists.org/t/video-sequence-editor-news-add-ons/1188770
Proposals etc.:
https://devtalk.blender.org/t/design-proposal-multicam-strips/12672
https://devtalk.blender.org/t/design-proposal-proxy-use-in-the-video-sequence-editor/12065
https://devtalk.blender.org/t/design-proposal-vse-toolbar/11650
https://devtalk.blender.org/t/gsoc-ideas-for-the-video-sequence-editor/11415
https://devtalk.blender.org/t/quick-tasks-for-the-video-sequence-editor-a-list-of-suggestions/10341
https://devtalk.blender.org/t/video-sequence-editor-a-list-of-ideas/10343

Good luck!
